### ISSUE TITLE
Support the abbr tag

### ISSUE THREAD

**Issue by xt0rted** [madskristensen/zencoding#40]
Currently `abbr` is expanded to `acronym` which isn't a supported tag in html5.

**Comment by am11** [comment]
Good catch! It seems like it is caused by this line: [HtmlElementFactory.cs#L155](https://github.com/madskristensen/zencoding/blob/d6013c9e5cde92207c63d2b3efd8b734c66fe813/ZenCoding/Html/HtmlElementFactory.cs#L155). We would need to separate this case.

Would you like to send a PR for fix?

**Comment by am11** [comment]
IMO, the smart fix would be to just replace:

```c#
using (HtmlGenericControl abbr = new HtmlGenericControl("acronym"))
```

with:

```c#
using (HtmlGenericControl abbr = new HtmlGenericControl(tagName))
```
